config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [destroy]
  end
  
  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: "about"
  
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create]
  end
  resources :users, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    defore_action :authenticate_admin!
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_deshboards_path, notice: 'ユーザーを削除しました。'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
    
    private
    
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
  def is_matching_login_user
     user = User.find(params[:id])
     unless user.id == current_user.id
       redirect_to post_images_path
     end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
    <label for="inputName">Name</label>
    <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
    <label for="inputImage">ProfileImage</label>
    <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
    <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div>
    <h3><%= @user.name %></h3>
    <%= image_tag @user.get_profile_image(100,100) %>
    <% if @user == user_signed_in? %>
    <p><%= link_to "プロフィール編集", edit_user_path %></p>
    <% end %>
</div>

<%= render 'post_images/list', post_images: @post_images %>