config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
  
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [destroy]
  end
  
  devise_for :users
  root to: "homes#top"
  get 'homes/about' => 'homes#about', as: "about"
  
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :post_comments, only: [:create]
  end
  resources :users, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  devise authentication_keys: [:email]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :post_image
    
    validates :user_id, uniqueness: {scope: :post_image_id}
    
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    
    belongs_to :user
    belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
    
    has_one_attached :image
    belongs_to :user
    has_many :post_comments,dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    validates :shop_name, presence: true
    validates :image,presence: true
    
    def get_image
        unless image.attached?
            file_path = Rails.root.goin('app/assets/images/no_image.jpg')
            image.attach(io: File.open(file_path), filename: 'default-image.jpg', contenttype: 'image/jpg')
        end
        image
    end
    
    def favorited_by?(user)
        favorites.exists?(user_id: user.id)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  layout 'admin'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  
  def after_sign_in_path_for(resouce)
    admin_dashboards_path # ログイン後にリダイレクトするパス
  end
  
  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path # ログアウト後にリダイレクトするパス
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    defore_action :authenticate_admin!
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_deshboards_path, notice: 'ユーザーを削除しました。'
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top], unless: :admin_controller?
    before_action :configure_permitted_parameters, if: :devise_controller?

     def after_sign_in_path_for(resource)
        post_images_path
     end
     
     def after_sign_out_path_for(resource)
        root_path
     end
     
     private
     
     def admin_controller?
         self.class.module_parent_name == 'admin'
     end
         
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def create
        post_image = PostImage.find(params[:post_image_id])
        favorite = current_user.favorites.new(post_image_id: post_image.id)
        favorite.save
        redirect_to post_image_path(post_image)
    end
    
    def destroy
        post_image = PostImage.find(params[:post_image_id])
        favorite = current_user.favorites.find_by(post_image_id: post_image.id)
        favorite.destroy
        redirect_to post_image_path(post_image)
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def new
        @post_imagee = "PostImage"
    end
    
    def index
    end
    
    def show
    end
    
    def about
    end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
    
    def create
        post_image = PostImage.find(params[:post_image_id])
        comment = current_user.post_comments.new(post_comment_params)
        comment.post_image_id = post_image.id
        comment.save
        redirect_to post_image_path(post_image)
    end
    
    private
    
    def post_comment_params
        params.require(:post_comment).permit(:comment)
    end
    
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def new
    @post_image = PostImage.new
  end
  
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_images_path
    else
      render :new
    end
  end

  def index
    @post_images = PostImage.page(params[:page])
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end
  
  def destroy
    post_image = PostImage.find(params[:id])
    post_image.destroy
    redirect_to '/post_images'
  end
  
  private
  
  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end
    
    private
    
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
  def is_matching_login_user
     user = User.find(params[:id])
     unless user.id == current_user.id
       redirect_to post_images_path
     end
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/post_images/_list.html.erb
<div classs="card-list-container py-5">
<% @post_images.each do |post_image| %>
    <div class="card w-50 mx-auto mt-4 shadow-lg">
      <%= link_to post_image_path(post_image.id) do %>
        <%= image_tag post_image.get_image, vlass: "card-img-top"; %>
      <% end %>
      <div class="card-body">
        <div class="row">
          <div cladd="col-2">
              <%= image_tag post_image.user.get_profile_image(100,100), class: "mt-3 rounded-circle"; %>
          </div>
          <div class="col-10">
            <p class="card-title">
              <%= link_to(post_image_path(post_image.id), class: "text-dark") do %>
                <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
              <% end %>
            </p>
            <p class="card-text">説明: <%= post_image.caption %></p>
            <span><i class="far fa-user"></i> By <%=post_image.user.name %> | </span>
            <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class: "text-dork" %></span>
          </div>
        </div>
      </div>
    </div>
<% end %>
<%= paginate post_images %>
</div>

app/views/post_images/index.html.erb
<%= render 'list', post_images: @post_images %>

app/views/post_images/new.html.erb
<div class="container">
    <div class="row no-gutters">
        <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
            <h5 class="text-dark bg-light p-4 mb-0">画像投稿フォーム</h5>
            <dib class="form-body p-4">
                <%= if @post_image.errors.any? %>
                  <ul class="alert alert-danger" rolw="alert">
                    <h6 class="alert-heading">
                        <%= @post_image.errors.count %>件のエラーが発生しました
                    </h6>
                    <% @post_image.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                <% end %>
                <%=form_with model: @post_image do |f| %>
                  <%= f.file_field :image, accept: "image/*", class: "w-100" %>
                  <div class="input-group mb-3 mt-4">
                      <div class="input-group-prepend">
                          <span class="input-group-text" aria-hedden="true"><i class="fas fa-building"></i></span>
                      </div>
                      <%= f.text.field :shop_name, class:"form-control", placeholder: "ショップ名" %>
                  </div>
                      <%= f.text_area :caption, class: "form-control", rows: "3", placeholder: "コメントここに" %>
                      <hr>
                      <%= f.submit '投稿', class: "btn btn-lg btn-block btn-info mt-4" %>
                    <% end %>
            </dib>
        </div>
    </div>
</div>

app/views/post_images/show.html.erb
<div>
    <%= image_tag @post_image.get_image %>
    <p>ショップ名：<%= @post_image.shop_name %></p>
    <p>説明：<%= @post_image.caption %></p>
    <p>投稿ユーザー画像：<%= image_tag @post_image.user.get_profile_image(100,100) %></p>
    <p>ユーザーネーム：<%= @post_image.user.name %></p>
    <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
    <% if @post_image.user == current_user %>
        <%= link_to "削除", post_image_path(@post_image), method: :delete %>
    <% end %>
    
    <% if @post_image.favorited_by?(current_user) %>
        <p>
        <%= link_to post_image_favorite_path(@post_image),method: :delete do %>
            ♥<%= @post_image.favorites.count %> いいね
        <% end %>
        </p>
        <% else %>
        <p>
        <%= link_to post_image_favorite_path(@post_image), method: :post do %>
            ♡<%=@post_image.favorites.count %> いいね
        <% end %>
        </p>
    <% end %>
</div>

<div>
    <p>コメント件数: <%= @post_image.post_comments.count %></p>
    <% @post_image.post_comments.each do |post_comment| %>
        <p><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
        <%= post_comment.user.name %>
        <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% end %>
</div>

<div>
    <%= form_with model:[@post_image, @post_comment] do |f| %>
        <%= f.text_area :comment, rows: '5',placeholder: "コメントをここに" %>
        <%= f.submit "送信する" %>
    <% end %>
</div>